name: Generate Documentation and Notify Slack

on: 
  push:
    branches: [master]
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Generate Documentation
        run: npx jsdoc -c jsdoc.json ./script.js -d docs # Configure in `jsdoc.json`

      - name: Archive Documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs

      - name: Notify Slack (Success)
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C077F0UFSJG'
          slack-message: |
            Documentation generated successfully! :page_facing_up:
            Check it out here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify Slack (Failure)
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C077F0UFSJG'
          slack-message: 'Documentation generation failed :x:' 
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
